FROM rh-registry.dso.techpark.local/ubi7/python-38

# copy src dir inside dssh dir of a container
WORKDIR /dssh
COPY --chown=2001:0 src/ .

# install all python requirements
WORKDIR ./seismiqb
RUN pip install --index=http://nexus.gazprom-neft.local:8080/repository/pypi-pypi-external-dso/simple \
                --trusted-host nexus.gazprom-neft.local \
                -r requirements.txt

# run main.py
WORKDIR ..
USER 2001
CMD ["python", "-u", "main.py"]

